my:
  id: ${MY_ID:0}

server:
  port: ${APP_PORT:8080}

mq:
  host: ${MQ_HOST:localhost}
  port: ${MQ_PORT:1414}}
  channel: ${MQ_CHANNEL:DEV.ADMIN.SVRCONN}
  qmgr: ${MQ_QMGR:QM}
  queue:
    name: ${MQ_QUEUE_NAME:DEV.QUEUE.1}
  app:
    name: ${MQ_APP_NAME:FIFO_APP}}
    user: ${MQ_APP_USER:admin}
    pswd: ${MQ_APP_PSWD:passw0rd}
db:
  mongo:
    url: ${DB_MONGO_URL:mongodb://localhost:27017}
    name: ${DB_MONGO_NAME:FIFO}
    user: ${DB_MONGO_USER:root}
    pswd: ${DB_MONGO_PSWD:password}
kafka:
  topic: fifo
  key: msg.key
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      fetch-max-wait: 1s
      fetch-min-size: 500000000
      max-poll-records: 5
      group-id: siTestGroup
      enable-auto-commit: true
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: biz.cits.mq.JavaSerializer
#    bootstrap-servers: Hardiks-MBP:8091,Hardiks-MBP:8092,Hardiks-MBPdoc:8093
    bootstrap-servers: Hardiks-MBP:9092